name: Ln test

on:
  push:
    branches:
      - *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go }}'

      - name: Test Ln
        run: go test -run TestLn
